version: 2.1
jobs:

  latest:
    executor: default
    steps:
      - build:
          version: "21.0"
          tag: latest

  java_8:
    executor: default
    steps:
      - build:
          version: "8.0"
          tag: java-8

  java_11:
    executor: default
    steps:
      - build:
          version: "11.0"
          tag: java-11

  java_17:
    executor: default
    steps:
      - build:
          version: "17.0"
          tag: java-17

  java_21:
    executor: default
    steps:
      - build:
          version: "21.0"
          tag: java-21

executors:

  default:
    docker:
      - image: cimg/base:stable

commands:

  build:
    parameters:
      version:
        type: string
        default: "21.0"
      tag:
        type: string
        default: "21.0"
        
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="23.0.6"
            sudo curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            sudo tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      - run:
          command: |
            docker build --build-arg "JAVA_VERSION=<< parameters.version >>" -t remie/circleci-collabsoft-addons:<< parameters.tag >> .
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push remie/circleci-collabsoft-addons:<< parameters.tag >>

workflows:
  deploy:
    jobs:
      - latest
      - java_8
      - java_11
      - java_17
      - java_21



