version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.1-ce"
            sudo curl -L -o /tmp/docker-\$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            sudo tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      - run:
          command: |
            docker build -t remie/circleci-collabsoft-addons:latest .
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push remie/circleci-collabsoft-addons:latest
  